[package]
name = "pac-color"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", default-features = false, features = ["gif", "ico", "jpeg", "png", "webp"] }
rocket = "0.5.1"

[profile.release]
strip = true
lto = true
